version: "3.9"

services:
  fastapi:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
