version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: user_management_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - user_management_network

  fastapi:
    build:
      context: .
    container_name: user_management_fastapi
    command: ["./startup.sh", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@postgres:5432/myappdb
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - user_management_network

networks:
  user_management_network:
    driver: bridge
