name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    name: Test with Pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.12] # Define Python versions here

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: myappdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Cache Python Dependencies
      - name: Cache Python Packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Set PYTHONPATH to fix ModuleNotFoundError
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=${PYTHONPATH}:$(pwd)" >> $GITHUB_ENV

      # Step 6: Run Tests with Pytest
      - name: Run Tests with Pytest
        env:
          DATABASE_URL: postgresql+asyncpg://user:password@localhost:5432/myappdb
        run: pytest

  build-and-push-docker:
    name: Build and Push Docker Image
    needs: test  # Ensures tests pass before building Docker image
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: saitejas0511@gmail.com
          password: Sailentt@55

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: saitejanagapuri/user_management_sai:${{ github.sha }} # Tag image with Git SHA
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=saitejanagapuri/user_management_sai:cache
          cache-to: type=inline,mode=max

      # Step 5: Scan Docker Image for Security Vulnerabilities
      - name: Scan the Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'saitejanagapuri/user_management_sai:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
