name: CI/CD Workflow

on:
  push:
    branches:
      - development

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Log in to DockerHub (set your secrets in GitHub repository settings)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: saitejas0511@gmail.com
        password: Sailentt@5555

    # Install Docker Compose
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin

    # Build and push Docker image
    - name: Build and Push Docker Image
      run: |
        docker build -t saitejanagapuri/user_management_sai-fastapi:latest .
        docker push saitejanagapuri/user_management_sai-fastapi:latest

    # Run Tests
    - name: Run Tests
      run: |
        docker-compose up -d
        docker-compose exec fastapi pytest --maxfail=1 --disable-warnings
        docker-compose down
