name: CI Pipeline

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: myappdb
        ports:
          - 5432:5432

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 4: Start Docker services
      - name: Start Docker services
        run: docker-compose up -d

      # Step 5: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 6: Run tests
      - name: Run Tests
        env:
          DATABASE_URL: postgresql+psycopg2://user:password@localhost:5432/myappdb
        run: |
          PYTHONPATH=./ pytest --maxfail=1 --disable-warnings

      # Step 7: Shutdown Docker Compose
      - name: Shutdown Docker Compose
        if: always()
        run: docker-compose down
