name: CI/CD Workflow

on:
  push:
    branches:
      - development

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: saitejas0511@gmail.com
          password: Sailentt@55

      # Ensure all containers are stopped
      - name: Stop existing containers
        run: |
          docker-compose down || true

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker-compose build
          docker tag user_management-fastapi:latest ${{ secrets.DOCKER_USERNAME }}/user_management-fastapi:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/user_management-fastapi:latest

      # Run tests
      - name: Run Tests
        run: |
          docker-compose up -d
          docker-compose exec fastapi pytest --maxfail=1 --disable-warnings
          docker-compose down
